name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        build_type: [ Debug, Release ]
        arch: [ Win32, x64 ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Build
      run: .\build.ps1 -mode ${{ matrix.build_type }} -arch ${{ matrix.arch }}
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: build-${{ matrix.build_type }}-${{ matrix.arch }}
        path: |
          ${{github.workspace}}\release
        retention-days: 30
