name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        build_type: [ Debug, Release ]
        arch: [ Win32, x64 ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Build
      run: .\build.ps1 -mode ${{ matrix.build_type }} -arch ${{ matrix.arch }}
    
    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        name: proxinject-snapshot-${{ github.sha }}-${{ matrix.build_type }}-${{ matrix.arch }}
        path: |
          ${{github.workspace}}\release
        retention-days: 30
    
    - name: Pack
      run: makensis /DVERSION=$(git describe --tags) .\setup.nsi
      if: ${{ matrix.build_type == 'Release' }}
    
    - name: Upload Package
      if: ${{ matrix.build_type == 'Release' }}
      uses: actions/upload-artifact@v3.0.0
      with:
        name: proxinject-snapshot-${{ github.sha }}-${{ matrix.arch }}-installer
        path: |
          ${{github.workspace}}\proxinjectSetup.exe
        retention-days: 30
